title: 区块链/云原生运维专家简历
description: 15年+资深运维专家 | 数字钱包/区块链基础设施建设
author: "你的名字"
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
  sass_dir: _sass
  style: compressed

