title: 李正彦 - 资深运维开发工程师
description: 15年+运维开发经验 | 专注于云原生/DevOps/SRE | 擅长自动化运维与架构设计
author: "李正彦"
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
  sass_dir: _sass
  style: compressed

